### ISSUE TITLE
Add section about "How to contact project maintainers"

### ISSUE THREAD

**Issue by Mariatta** [KatherineMichel/setting-up-an-open-source-project#2]
I think it's important for new contributors to know who the maintainers/core developers are, and how to contact them. Especially when there is an organization involved (not a personal repo)
Maybe in readme template, the maintainer contact info should be one of the first things listed?

Some ideas:
- Name, role, contact info (twitter handle, email address, or mailing list address )
- link to slack/gitter/irc channel where devs can be reached.

Opening an issue works, but sometimes newcomers may not feel comfortable asking questions publicly (I have this problem myself).

**Comment by KatherineMichel** [comment]
Awesome idea. Can you add it to the README template and make a pull request and I can review it?  :)
